<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SharpProsperoRoot)/build/Prospero.App.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MMEngine.InputDemo</AssemblyName>
    <RootNamespace>MMEngine.Samples.InputDemo</RootNamespace>
    <ProsperoModuleName>eboot.bin</ProsperoModuleName>
    <ProsperoHeapHardLimitBytes>268435456</ProsperoHeapHardLimitBytes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MMEngine.Platform.PS5/MMEngine.Platform.PS5.csproj" />
    <ProjectReference Include="$(SharpProsperoRoot)/src/SharpProspero/SharpProspero.csproj" />
    <None Update="sce_sys/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Import Project="$(SharpProsperoRoot)/build/Prospero.App.targets" />
  <Import Project="../../build/MMEngine.PackageAssets.targets" />
</Project>
