<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MMEngine.Graphics3D</AssemblyName>
    <RootNamespace>MMEngine.Graphics3D</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MMEngine.Core/MMEngine.Core.csproj" />
    <ProjectReference Include="../MMEngine.Scene/MMEngine.Scene.csproj" />
    <ProjectReference Include="../MMEngine.Assets/MMEngine.Assets.csproj" />
    <ProjectReference Include="$(SharpProsperoRoot)/src/SharpProspero/SharpProspero.csproj" />
  </ItemGroup>
</Project>
